name       : wacomtablet
version    : 3.0.0
release    : 1
source     :
    - https://cdn.download.kde.org/stable/wacomtablet/3.0.0/wacomtablet-3.0.0.tar.xz : 1c9380f65782b4926da5de70bf99c6be5afd166981a51831dabaf7753b4b5c17
license    : GPL-2.0-or-later
component  : desktop.kde
summary    : Wacomtablet is a collection of tools for setting up graphical tablet in KDE
description: |
    This module implements a GUI for the Wacom Linux Drivers and extends it with profile support to handle different button / pen layouts per profile.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5QuickControls2)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(xi)
    - pkgconfig(xorg-wacom)
    - extra-cmake-modules
    - kcoreaddons-devel
    - kdbusaddons-devel
    - kdoctools-devel
    - kglobalaccel-devel
    - ki18n-devel
    - knotifications-devel
    - kwidgetsaddons-devel
    - kwindowsystem-devel
    - kxmlgui-devel
    - plasma-framework-devel
    - xorg-server-xvfb
rundeps    :
    - xorg-driver-input-wacom
setup      : |
    %cmake_ninja -DBUILD_TESTING=ON
build      : |
    %ninja_build
install    : |
    %ninja_install
    %qml_cache
check      : |
    pushd solusBuildDir
    # dbus test fails (solbuild doesn't support dbus yet)
    xvfb-run ctest || :
